# default balance of 10,000 ether to simplify testing of ETH pools
networks:
  development:
    cmd_settings:
      default_balance: 10000
  rinkeby:
    host: https://rinkeby.infura.io/v3/f55e80a3523b48feb3ef8e4a0c9f5bcc
  

# exclude non-core contracts from coverage analysis
reports:
  exclude_paths:
    - contracts/testing/*.*
    - contracts/gauges/*.*

dependencies:
  - curvefi/curve-dao-contracts@1.2.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    version: 0.8.4
    remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"

hypothesis:
  phases:
    explicit: true
    reuse: false
    generate: true
    target: false
    shrink: false

autofetch_sources: true


